=== tharikaGitHub/FastTrack/XMLFastTrack/out/production/XMLValidator/book.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ /*
  ~ *  Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
  ~ *
  ~ *  WSO2 Inc. licenses this file to you under the Apache License,
  ~ *  Version 2.0 (the "License"); you may not use this file except
  ~ *  in compliance with the License.
  ~ *  You may obtain a copy of the License at
  ~ *
  ~ *    http://www.apache.org/licenses/LICENSE-2.0
  ~ *
  ~ * Unless required by applicable law or agreed to in writing,
  ~ * software distributed under the License is distributed on an
  ~ * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ * KIND, either express or implied.  See the License for the
  ~ * specific language governing permissions and limitations
  ~ * under the License.
  ~ */
  -->

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <!-- Simple elements-->
    <xs:element name="title" type="xs:string"/>
    <xs:element name="author" type="xs:string"/>
    <xs:element name="price" type="xs:string"/>

    <!-- Attributes -->
    <xs:attribute name="id" type="xs:string"/>

    <!-- Complex elements -->
    <xs:element name="catalog">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="title"/>
                            <xs:element ref="author"/>
                            <xs:element ref="price"/>
                        </xs:sequence>
                        <xs:attribute ref="id" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== tharikaGitHub/FastTrack/XMLFastTrack/out/production/XMLValidator/book.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ /*
  ~ *  Copyright (c) 2017, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
  ~ *
  ~ *  WSO2 Inc. licenses this file to you under the Apache License,
  ~ *  Version 2.0 (the "License"); you may not use this file except
  ~ *  in compliance with the License.
  ~ *  You may obtain a copy of the License at
  ~ *
  ~ *    http://www.apache.org/licenses/LICENSE-2.0
  ~ *
  ~ * Unless required by applicable law or agreed to in writing,
  ~ * software distributed under the License is distributed on an
  ~ * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  ~ * KIND, either express or implied.  See the License for the
  ~ * specific language governing permissions and limitations
  ~ * under the License.
  ~ */
  -->

<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="book.xsd">
    <book id="DC_CD_1">
        <title>David Copperfield</title>
        <author>Charles Dickens</author>
        <price>$10.00</price>
    </book>
    <book id="MD_HM_1">
        <title>Moby-Dick</title>
        <author>Herman Melville</author>
        <price>$15.30</price>
    </book>
    <book id="WH_EB_1">
        <title>Wuthering Heights</title>
        <author>Emily Bronte</author>
        <price>$12.00</price>
    </book>
    <book id="PD_JA_1">
        <title>Pride and Prejudice</title>
        <author>Jane Austen</author>
        <price>$18.50</price>
    </book>
    <book id="WP_T_1">
        <title>War and Peace</title>
        <author>Tolstoy</author>
        <price>$16.30</price>
    </book>
</catalog>
